export const mySkills = [
  { title: "Flutter", icon: "flutter" },
  { title: "Dart", icon: "dart" },
  { title: "Laravel", icon: "laravel" },
  { title: "PHP", icon: "php" },
  { title: "MySQL", icon: "mysql" },
  { title: "PostgreSQL", icon: "postgresql" },
  { title: "Firebase", icon: "firebase" },
  { title: "AWS", icon: "aws" },
  { title: "S3", icon: "s3" },
  { title: "CloudFront", icon: "cloudfront" },
  { title: "Lambda", icon: "lambda" },
  { title: "API Gateway", icon: "apigateway" },
  { title: "Cognito", icon: "cognito" },
  { title: "Node.js", icon: "nodejs" },
  { title: "NestJS", icon: "nestjs" },
  { title: "TypeORM", icon: "typeorm" },
  { title: "Prisma", icon: "prisma" },
  { title: "React Native", icon: "reactnative" },
  { title: "Expo", icon: "expo" },
  { title: "React", icon: "react" },
  { title: "Next.js", icon: "nextjs" },
  { title: "JavaScript", icon: "javascript" },
  { title: "TypeScript", icon: "typescript" },
  { title: "Tailwind CSS", icon: "tailwind" },
  { title: "shadcn/ui", icon: "shadcn" },
  { title: "HTML", icon: "html" },
  { title: "CSS", icon: "css" },
  { title: "ExpressJS", icon: "express" },
  { title: "MongoDB", icon: "mongodb" },
  { title: "Git", icon: "git" },
  { title: "GitHub", icon: "gitHub" },
  { title: "Vercel", icon: "vercel" },
  { title: "Postman", icon: "postman" },
  { title: "Linux", icon: "linux" },
  { title: "macOS", icon: "macos" },
  { title: "Windows", icon: "windows" },
  { title: "pnpm", icon: "pnpm" },
  { title: "npm", icon: "npm" },
  { title: "yarn", icon: "yarn" },
  { title: "Docker", icon: "docker" },
  { title: "Radix UI", icon: "radix" },
];
